//
// Generated file, do not edit! Created by nedtool 4.6 from src/networklayer/CIDERNet/RLL/common/RLLControlInfo.msg.
//

#ifndef _RLLCONTROLINFO_M_H_
#define _RLLCONTROLINFO_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    using namespace std;
// }}

/**
 * Class generated from <tt>src/networklayer/CIDERNet/RLL/common/RLLControlInfo.msg:21</tt> by nedtool.
 * <pre>
 * message RLLControlInfo
 * {
 * }
 * </pre>
 */
class RLLControlInfo : public ::cMessage
{
  protected:

  private:
    void copy(const RLLControlInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RLLControlInfo&);

  public:
    RLLControlInfo(const char *name=NULL, int kind=0);
    RLLControlInfo(const RLLControlInfo& other);
    virtual ~RLLControlInfo();
    RLLControlInfo& operator=(const RLLControlInfo& other);
    virtual RLLControlInfo *dup() const {return new RLLControlInfo(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, RLLControlInfo& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RLLControlInfo& obj) {obj.parsimUnpack(b);}


#endif // ifndef _RLLCONTROLINFO_M_H_

