//
// Generated file, do not edit! Created by nedtool 4.6 from src/linklayer/mac/CCSMA/CCSMAFrame.msg.
//

#ifndef _CCSMAFRAME_M_H_
#define _CCSMAFRAME_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "Ieee802154Frame_m.h";
// }}

/**
 * Class generated from <tt>src/linklayer/mac/CCSMA/CCSMAFrame.msg:9</tt> by nedtool.
 * <pre>
 * packet CCSMAFrame extends Ieee802154Frame
 * {
 *     //	MHR
 *     //	Frame control fieled (FCF)(16 bits) - Fig 35
 *     int HopCount;
 * 
 * 		//	MFR
 * 		//	FCS is not modeled and only included in the length (2 bytes)
 * }
 * </pre>
 */
class CCSMAFrame : public ::Ieee802154Frame
{
  protected:
    int HopCount_var;

  private:
    void copy(const CCSMAFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CCSMAFrame&);

  public:
    CCSMAFrame(const char *name=NULL, int kind=0);
    CCSMAFrame(const CCSMAFrame& other);
    virtual ~CCSMAFrame();
    CCSMAFrame& operator=(const CCSMAFrame& other);
    virtual CCSMAFrame *dup() const {return new CCSMAFrame(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getHopCount() const;
    virtual void setHopCount(int HopCount);
};

inline void doPacking(cCommBuffer *b, CCSMAFrame& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CCSMAFrame& obj) {obj.parsimUnpack(b);}


#endif // ifndef _CCSMAFRAME_M_H_

